filebeat.inputs:

  - input_type: log
    paths:
      - /var/log/json*.log*
    tags: ["app1"]

  - input_type: log
    paths:
      - /var/log/test*.log*
    tags: ["app2"]

output.logstash:
  hosts: ["logstash:5044"]
